version: "3.9"

services:
  db:
    image: postgres:15
    container_name: nursequest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nursequest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: nursequest-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-data:
